### ISSUE TITLE
Metrics with list state cause crash using ddp

### ISSUE THREAD

**Issue by fuine** [PyTorchLightning/metrics#337]
### To Reproduce

1. Install torchmetrics 0.4, PyTorch Lightning 1.3.7
2.  Run the script below

#### Code sample

```python
import os

import torch
from torch.utils.data import DataLoader, Dataset

from pytorch_lightning import LightningModule, Trainer
from torchmetrics import CosineSimilarity


class RandomDataset(Dataset):

    def __init__(self, size, length):
        self.len = length
        self.data = torch.randn(length, size)

    def __getitem__(self, index):
        return self.data[index]

    def __len__(self):
        return self.len


class BoringModel(LightningModule):

    def __init__(self):
        super().__init__()
        self.layer = torch.nn.Linear(32, 2)
        self.metric = CosineSimilarity()  # add this to break it all

    def forward(self, x):
        return self.layer(x)

    def training_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("train_loss/train", loss)
        return loss

    def configure_optimizers(self):
        return torch.optim.SGD(self.layer.parameters(), lr=0.1)


def run():
    train_data = DataLoader(RandomDataset(32, 64), batch_size=2)

    model = BoringModel()
    trainer = Trainer(
        default_root_dir=os.getcwd(),
        limit_train_batches=1,
        max_epochs=1,
        weights_summary=None,
        accelerator="ddp",
        gpus=2,
    )
    trainer.fit(model, train_dataloader=train_data)


if __name__ == '__main__':
    run()
```
<details>
<summary>Raw output/traceback from the script</summary>

```
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
initializing ddp: GLOBAL_RANK: 1, MEMBER: 2/2
initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/2
[W ProcessGroupNCCL.cpp:1569] Rank 0 using best-guess GPU 0 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device.
[W ProcessGroupNCCL.cpp:1569] Rank 1 using best-guess GPU 1 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device.
LOCAL_RANK: 1 - CUDA_VISIBLE_DEVICES: [0,1]
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]
Traceback (most recent call last):
  File "list_crash_dummy.py", line 58, in <module>
    run()
  File "list_crash_dummy.py", line 54, in run
    trainer.fit(model, train_dataloader=train_data)
  File "<venv>/site-packages/pytorch_lightning/trainer/trainer.py", line 458, in fit
    self._run(model)
  File "<venv>/site-packages/pytorch_lightning/trainer/trainer.py", line 753, in _run
    self.pre_dispatch()
  File "<venv>/site-packages/pytorch_lightning/trainer/trainer.py", line 778, in pre_dispatch
    self.accelerator.pre_dispatch(self)
  File "<venv>/site-packages/pytorch_lightning/accelerators/accelerator.py", line 108, in pre_dispatch
    self.training_type_plugin.pre_dispatch()
  File "<venv>/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 281, in pre_dispatch
    self.configure_ddp()
  File "<venv>/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 253, in configure_ddp
    self._model = DistributedDataParallel(
  File "<venv>/site-packages/torch/nn/parallel/distributed.py", line 498, in __init__
    self._sync_params_and_buffers(authoritative_rank=0)
  File "<venv>/site-packages/torch/nn/parallel/distributed.py", line 509, in _sync_params_and_buffers
    for name, param in self.module.state_dict().items():
  File "<venv>/site-packages/torch/nn/modules/module.py", line 1259, in state_dict
    module.state_dict(destination, prefix + name + '.', keep_vars=keep_vars)
  File "<venv>/site-packages/torch/nn/modules/module.py", line 1259, in state_dict
    module.state_dict(destination, prefix + name + '.', keep_vars=keep_vars)
  File "<venv>/site-packages/torchmetrics/metric.py", line 421, in state_dict
    with self.sync_context(dist_sync_fn=self.dist_sync_fn):
  File "<venv>/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "<venv>/site-packages/torchmetrics/metric.py", line 299, in sync_context
    cache = self.sync(
  File "<venv>/site-packages/torchmetrics/metric.py", line 272, in sync
    self._sync_dist(dist_sync_fn, process_group=process_group)
  File "<venv>/site-packages/torchmetrics/metric.py", line 222, in _sync_dist
    if isinstance(output_dict[attr][0], Tensor):
IndexError: list index out of range
Traceback (most recent call last):
  File "list_crash_dummy.py", line 58, in <module>
    run()
  File "list_crash_dummy.py", line 54, in run
    trainer.fit(model, train_dataloader=train_data)
  File "<venv>/site-packages/pytorch_lightning/trainer/trainer.py", line 458, in fit
    self._run(model)
  File "<venv>/site-packages/pytorch_lightning/trainer/trainer.py", line 753, in _run
    self.pre_dispatch()
  File "<venv>/site-packages/pytorch_lightning/trainer/trainer.py", line 778, in pre_dispatch
    self.accelerator.pre_dispatch(self)
  File "<venv>/site-packages/pytorch_lightning/accelerators/accelerator.py", line 108, in pre_dispatch
    self.training_type_plugin.pre_dispatch()
  File "<venv>/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 281, in pre_dispatch
    self.configure_ddp()
  File "<venv>/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 253, in configure_ddp
    self._model = DistributedDataParallel(
  File "<venv>/site-packages/torch/nn/parallel/distributed.py", line 498, in __init__
    self._sync_params_and_buffers(authoritative_rank=0)
  File "<venv>/site-packages/torch/nn/parallel/distributed.py", line 509, in _sync_params_and_buffers
    for name, param in self.module.state_dict().items():
  File "<venv>/site-packages/torch/nn/modules/module.py", line 1259, in state_dict
    module.state_dict(destination, prefix + name + '.', keep_vars=keep_vars)
  File "<venv>/site-packages/torch/nn/modules/module.py", line 1259, in state_dict
    module.state_dict(destination, prefix + name + '.', keep_vars=keep_vars)
  File "<venv>/site-packages/torchmetrics/metric.py", line 421, in state_dict
    with self.sync_context(dist_sync_fn=self.dist_sync_fn):
  File "<venv>/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "<venv>/site-packages/torchmetrics/metric.py", line 299, in sync_context
    cache = self.sync(
  File "<venv>/site-packages/torchmetrics/metric.py", line 272, in sync
    self._sync_dist(dist_sync_fn, process_group=process_group)
  File "<venv>/site-packages/torchmetrics/metric.py", line 222, in _sync_dist
    if isinstance(output_dict[attr][0], Tensor):
IndexError: list index out of range
```
</details>

#### A few important notes:
* All you have to do is `self.metric = CosineSimilarity()`, then it will break. You don't have to use the metric, just assign it.
* This bug shows up for any metric that uses a list instance as its state
* I know that it looks very similar to #331 (the code differs only in the type of the metric and accelerator) but I think this is a separate issue

### Expected behavior

The script should run

### Environment

 - PyTorch Version (e.g., 1.0): 1.9.0
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): `pip` via `poetry`
 - Build command you used (if compiling from source):
 - Python version: 3.8.6
 - CUDA/cuDNN version: 10.2
 - GPU models and configuration: 2x RTX 2070
 - Any other relevant information:

**Comment by ethanwharris** [comment]
Possibly related to PyTorchLightning/pytorch-lightning#8227

**Comment by ethanwharris** [comment]
Hi @fuine, I think this should have been fixed with torchmetrics master. Could try installing with:
```
pip install https://github.com/PyTorchLightning/metrics/archive/master.zip
```
and see if the error goes?

**Comment by fuine** [comment]
Hi @ethanwharris, I'm afraid it still crashes on master :slightly_frowning_face: From what I could gather with a quick debugging session and a **very**  limited knowledge of pl/torchmetrics the issue is that the sync is called on an empty state and the `output_dict` has an empty list for the state. The code then tries to asses the inner type of the state element, and does so by checking the type of the first element, which obviously is not existant

**Comment by SkafteNicki** [comment]
Hi @fuine,
Could you please checkout the fix in PR #338 and see if that fixes your problem

**Comment by fuine** [comment]
Hi @SkafteNicki it does solve the problem - the code runs

**Comment by Borda** [comment]
closed by #339
